name: "Test and Build"

on:
  push:
    branches:
    - main

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        make dependencies
    - name: Install Test Dependencies
      run : make tests-dependencies

    - name: Check Codestyle
      run: make check-codestyle

    - name: Check Docstyle
      run: make check-docstyle

    - name: Check Code Metrics
      run: make check-codemetrics

    - name: Check Security Issues
      run: make check-security

    - name: Check Dependency Security
      run: make check-dependencies

    - name: Check Static Analysis
      run: make check-pytype

    - name: Run Unit Tests
      run: make tests-reports

    - name: Archive Unit Test Report
      uses: actions/upload-artifact@v1
      with:
        name: unit-tests-report
        path: reports/unit_tests

    - name: Archive Code Coverage Report
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: reports/coverage
